### ISSUE TITLE
Pretrained Model of Stereo Training

### ISSUE THREAD

**Issue by ldkong1205** [kamiLight/CADepth-master#4]
Hi @kamiLight, thank you for open-sourcing this work!

I would like to ask if CADepth can be trained with the stereo option. If so then could you share the pretrained weights? Thanks!

**Comment by kamiLight** [comment]
there is no trained weights beacuse we didn't perform the experiment on stereo images, but you can  run `python train.py --model_name stereo_model  --frame_ids 0 --use_stereo --split eigen_full` and train the CADepth with stereo images by yourself

**Comment by ldkong1205** [comment]
> there is no trained weights beacuse we didn't perform the experiment on stereo images, but you can run `python train.py --model_name stereo_model --frame_ids 0 --use_stereo --split eigen_full` and train the CADepth with stereo images by yourself

Noted with thanks!
